//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountAuthority = new HashSet<AccountAuthority>();
        }
    
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public int AccountType { get; set; }
    
        public virtual ICollection<AccountAuthority> AccountAuthority { get; set; }
        public virtual AdminPerson AdminPerson { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
