//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChinaCounty
    {
        public ChinaCounty()
        {
            this.Community = new HashSet<Community>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int Id { get; set; }
        public int CityId { get; set; }
        public string Name { get; set; }
    
        public virtual ChinaCity ChinaCity { get; set; }
        public virtual ICollection<Community> Community { get; set; }
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
