//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityShop
    {
        public int Id { get; set; }
        public Nullable<int> CommunityId { get; set; }
        public Nullable<int> ShopId { get; set; }
    
        public virtual Community Community { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
