//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Community
    {
        public Community()
        {
            this.CommunityShop = new HashSet<CommunityShop>();
        }
    
        public int Id { get; set; }
        public int CountyId { get; set; }
        public string FirstLetter { get; set; }
        public string Name { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
    
        public virtual ChinaCounty ChinaCounty { get; set; }
        public virtual ICollection<CommunityShop> CommunityShop { get; set; }
    }
}
