//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.OrderHead = new HashSet<OrderHead>();
            this.RecipientAddress = new HashSet<RecipientAddress>();
            this.CashBack = new HashSet<CashBack>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<OrderHead> OrderHead { get; set; }
        public virtual ICollection<RecipientAddress> RecipientAddress { get; set; }
        public virtual ICollection<CashBack> CashBack { get; set; }
    }
}
