//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBody
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int SkuId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual OrderHead OrderHead { get; set; }
        public virtual Sku Sku { get; set; }
    }
}
