//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHead
    {
        public OrderHead()
        {
            this.OrderBody = new HashSet<OrderBody>();
        }
    
        public int Id { get; set; }
        public int Status { get; set; }
        public string OrderNumber { get; set; }
        public int FromDeviceType { get; set; }
        public int ShopId { get; set; }
        public int CustomerId { get; set; }
        public int AddressId { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public string Remarks { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderBody> OrderBody { get; set; }
        public virtual RecipientAddress RecipientAddress { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
