//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHead
    {
        public OrderHead()
        {
            this.OrderBody = new HashSet<OrderBody>();
        }
    
        public int Id { get; set; }
        public int Status { get; set; }
        public string OrderNumber { get; set; }
        public int FromDeviceType { get; set; }
        public int ShopId { get; set; }
        public int CustomerId { get; set; }
        public int AddressId { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public string Remarks { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderBody> OrderBody { get; set; }
        public virtual RecipientAddress RecipientAddress { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
