//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipientAddress
    {
        public RecipientAddress()
        {
            this.OrderHead = new HashSet<OrderHead>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string DetailAddress { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderHead> OrderHead { get; set; }
    }
}
