//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.CommunityShop = new HashSet<CommunityShop>();
            this.OrderHead = new HashSet<OrderHead>();
            this.Sku = new HashSet<Sku>();
        }
    
        public int Id { get; set; }
        public int CountyId { get; set; }
        public bool IsIntegral { get; set; }
        public string Name { get; set; }
        public string DetailAddress { get; set; }
        public string ContactName { get; set; }
        public Nullable<SE.Common.Types.GenderType> ContactGender { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string TelePhoneNumber { get; set; }
        public Nullable<int> DeliveryMinAmount { get; set; }
        public Nullable<int> DeliveryRate { get; set; }
        public string ImageFileName { get; set; }
        public SE.Common.Types.ShopCooperationStatus CooperationStatus { get; set; }
        public Nullable<System.DateTime> TemporaryClosingBeginDate { get; set; }
        public Nullable<System.DateTime> TemporaryClosingEndDate { get; set; }
        public Nullable<System.TimeSpan> DailyClosingTime { get; set; }
        public Nullable<System.DateTime> ShopOpenDateTime { get; set; }
        public Nullable<System.TimeSpan> DailyOpeningTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ChinaCounty ChinaCounty { get; set; }
        public virtual ICollection<CommunityShop> CommunityShop { get; set; }
        public virtual ICollection<OrderHead> OrderHead { get; set; }
        public virtual ICollection<Sku> Sku { get; set; }
    }
}
