//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopTest10Entities : DbContext
    {
        public ShopTest10Entities()
            : base("name=ShopTest10Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<AccountAuthority> AccountAuthority { get; set; }
        public DbSet<AdminPerson> AdminPerson { get; set; }
        public DbSet<Authority> Authority { get; set; }
        public DbSet<Brand> Brand { get; set; }
        public DbSet<BrandSkuType> BrandSkuType { get; set; }
        public DbSet<ChinaCity> ChinaCity { get; set; }
        public DbSet<ChinaCounty> ChinaCounty { get; set; }
        public DbSet<ChinaProvince> ChinaProvince { get; set; }
        public DbSet<Community> Community { get; set; }
        public DbSet<CommunityShop> CommunityShop { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<OrderBody> OrderBody { get; set; }
        public DbSet<OrderHead> OrderHead { get; set; }
        public DbSet<RecipientAddress> RecipientAddress { get; set; }
        public DbSet<Shop> Shop { get; set; }
        public DbSet<Sku> Sku { get; set; }
        public DbSet<SkuCategory> SkuCategory { get; set; }
        public DbSet<SkuType> SkuType { get; set; }
        public DbSet<SkuUnit> SkuUnit { get; set; }
        public DbSet<CashBack> CashBack { get; set; }
    }
}
