//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sku
    {
        public Sku()
        {
            this.OrderBody = new HashSet<OrderBody>();
        }
    
        public int Id { get; set; }
        public bool IsPublic { get; set; }
        public Nullable<int> ShopId { get; set; }
        public int SkuCategoryId { get; set; }
        public int SkuTypeId { get; set; }
        public int BrandId { get; set; }
        public int UnitId { get; set; }
        public string Name { get; set; }
        public string SupplierName { get; set; }
        public string Specification { get; set; }
        public decimal Price { get; set; }
        public decimal DiscountPrice { get; set; }
        public string ImageFileName { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<OrderBody> OrderBody { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual SkuCategory SkuCategory { get; set; }
        public virtual SkuType SkuType { get; set; }
        public virtual SkuUnit SkuUnit { get; set; }
    }
}
